#    COPYRIGHT (C) 2024 Mitsubishi Electric Corporation

#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at

#        http://www.apache.org/licenses/LICENSE-2.0

#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

controller_manager:
  ros__parameters:
    update_rate: 286  #Hz

    rv5as_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gpio_controller:
      type: melfa_io_controllers/MelfaGPIOController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

rv5as_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - rv5as_joint_1
      - rv5as_joint_2
      - rv5as_joint_3
      - rv5as_joint_4
      - rv5as_joint_5
      - rv5as_joint_6

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

gpio_controller:
  ros__parameters:
    hand_io_state_interfaces:
      - hand_io/bit_id
      - hand_io/bit_mask
      - hand_io/bit_send_type
      - hand_io/input_data
      - hand_io/output_data
    plc_link_io_state_interfaces:
      - plc_link_io/bit_id
      - plc_link_io/bit_mask
      - plc_link_io/bit_send_type
      - plc_link_io/input_data
      - plc_link_io/output_data
    safety_io_state_interfaces:
      - safety_io/bit_id
      - safety_io/bit_mask
      - safety_io/bit_send_type
      - safety_io/input_data
      - safety_io/output_data
    io_unit_state_interfaces:
      - io_unit/bit_id
      - io_unit/bit_mask
      - io_unit/bit_send_type
      - io_unit/input_data
      - io_unit/output_data
    misc1_io_state_interfaces:
      - misc1_io/bit_id
      - misc1_io/bit_mask
      - misc1_io/bit_send_type
      - misc1_io/input_data
      - misc1_io/output_data
    misc2_io_state_interfaces:
      - misc2_io/bit_id
      - misc2_io/bit_mask
      - misc2_io/bit_send_type
      - misc2_io/input_data
      - misc2_io/output_data
    misc3_io_state_interfaces:
      - misc3_io/bit_id
      - misc3_io/bit_mask
      - misc3_io/bit_send_type
      - misc3_io/input_data
      - misc3_io/output_data
    misc_io_state_interfaces:
      - io_control_mode/io_mode
      - ctrl/ctrl_type
    hand_io_command_interfaces:
      - hand_io/bit_id
      - hand_io/bit_mask
      - hand_io/bit_recv_type
      - hand_io/bit_send_type
      - hand_io/output_data
    plc_link_io_command_interfaces:
      - plc_link_io/bit_id
      - plc_link_io/bit_mask
      - plc_link_io/bit_recv_type
      - plc_link_io/bit_send_type
      - plc_link_io/output_data
    safety_io_command_interfaces:
      - safety_io/bit_id
      - safety_io/bit_mask
      - safety_io/bit_recv_type
      - safety_io/bit_send_type
      - safety_io/output_data
    io_unit_command_interfaces:
      - io_unit/bit_id
      - io_unit/bit_mask
      - io_unit/bit_recv_type
      - io_unit/bit_send_type
      - io_unit/output_data
    misc1_io_command_interfaces:
      - misc1_io/bit_id
      - misc1_io/bit_mask
      - misc1_io/bit_recv_type
      - misc1_io/bit_send_type
      - misc1_io/output_data
    misc2_io_command_interfaces:
      - misc2_io/bit_id
      - misc2_io/bit_mask
      - misc2_io/bit_recv_type
      - misc2_io/bit_send_type
      - misc2_io/output_data
    misc3_io_command_interfaces:
      - misc3_io/bit_id
      - misc3_io/bit_mask
      - misc3_io/bit_recv_type
      - misc3_io/bit_send_type
      - misc3_io/output_data
    misc_io_command_interfaces:
      - io_control_mode/io_mode
      - ctrl/ctrl_type

forward_position_controller:
  ros__parameters:
    joints:
      - rv5as_joint_1
      - rv5as_joint_2
      - rv5as_joint_3
      - rv5as_joint_4
      - rv5as_joint_5
      - rv5as_joint_6

    interface_name: position
